import type { Review } from '../modules/reviews/review.js'

/**
 * Ulasan awal untuk adapter in-memory, terpisah agar seed bukan bagian dari
 * aturan penyimpanan repository. Satu game sengaja dibiarkan tanpa ulasan
 * supaya empty state ikut terlihat tanpa perlu menghapus data.
 */
export const seededReviews: readonly Review[] = [
	{
		id: 'review-elden-1',
		gameId: 'elden-ring',
		reviewerName: 'Jordan Lee',
		text: 'Desain dunianya membuat setiap belokan yang tidak direncanakan terasa berharga.',
		rating: 5,
		createdAt: '2025-01-15T14:00:00.000Z',
	},
	{
		id: 'review-elden-2',
		gameId: 'elden-ring',
		reviewerName: 'Samira Patel',
		text: 'Luas dan sulit, tapi rasa penasaran hampir selalu dibayar tuntas.',
		rating: 5,
		createdAt: '2025-01-20T09:30:00.000Z',
	},
	{
		id: 'review-hades-1',
		gameId: 'hades',
		reviewerName: 'Maya Chen',
		text: 'Ronde yang cepat dan progres yang murah hati membuat kalah tetap menyenangkan.',
		rating: 5,
		createdAt: '2025-01-18T17:45:00.000Z',
	},
	{
		id: 'review-astro-1',
		gameId: 'astro-bot',
		reviewerName: 'Nadia Farrell',
		text: 'Pendek, tapi hampir setiap level memperkenalkan satu ide lalu pensiun sebelum bosan.',
		rating: 5,
		createdAt: '2025-01-26T13:40:00.000Z',
	},
	{
		id: 'review-astro-2',
		gameId: 'astro-bot',
		reviewerName: 'Rangga Mahendra',
		text: 'Kontrolnya presisi. Anak saya bisa main tanpa saya jelaskan apa pun.',
		rating: 5,
		createdAt: '2025-01-28T08:15:00.000Z',
	},
	{
		id: 'review-balatro-1',
		gameId: 'balatro',
		reviewerName: 'Ivan Kurniawan',
		text: 'Niat main satu ronde, tiba-tiba sudah jam dua pagi. Hati-hati.',
		rating: 5,
		createdAt: '2025-01-27T22:05:00.000Z',
	},
	{
		id: 'review-balatro-2',
		gameId: 'balatro',
		reviewerName: 'Sinta Dewi',
		text: 'Tampilannya sederhana, tapi kombinasinya dalam sekali begitu paham jokernya.',
		rating: 4,
		createdAt: '2025-01-29T19:30:00.000Z',
	},
	{
		id: 'review-ffvii-1',
		gameId: 'final-fantasy-vii-rebirth',
		reviewerName: 'Clara Mendes',
		text: 'Pertarungannya luar biasa. Minigame-nya kadang terlalu banyak menahan alur.',
		rating: 4,
		createdAt: '2025-01-25T11:20:00.000Z',
	},
	{
		id: 'review-baldurs-1',
		gameId: 'baldurs-gate-3',
		reviewerName: 'Putri Rahmawati',
		text: 'Setiap rencana nekat yang saya karang ditangani oleh aturannya, bukan ditolak.',
		rating: 5,
		createdAt: '2025-01-22T11:15:00.000Z',
	},
	{
		id: 'review-baldurs-2',
		gameId: 'baldurs-gate-3',
		reviewerName: 'Tomas Nowak',
		text: 'Babak ketiga agak melambat, tapi para companion-nya menyelamatkan keadaan.',
		rating: 4,
		createdAt: '2025-01-24T08:05:00.000Z',
	},
	{
		id: 'review-totk-1',
		gameId: 'tears-of-the-kingdom',
		reviewerName: 'Arif Santoso',
		text: 'Merakit kendaraan sendiri membuat saya berhenti mencari jalan yang benar.',
		rating: 5,
		createdAt: '2025-01-23T15:10:00.000Z',
	},
	{
		id: 'review-alan-wake-1',
		gameId: 'alan-wake-2',
		reviewerName: 'Grace Okafor',
		text: 'Atmosfernya pekat. Saya harus main siang hari, dan itu pujian.',
		rating: 5,
		createdAt: '2025-01-21T20:45:00.000Z',
	},
	{
		id: 'review-ragnarok-1',
		gameId: 'god-of-war-ragnarok',
		reviewerName: 'Dani Prasetyo',
		text: 'Porsi Atreus mengejutkan, dan justru bagian itu yang paling saya ingat.',
		rating: 5,
		createdAt: '2025-01-19T18:00:00.000Z',
	},
	{
		id: 'review-ragnarok-2',
		gameId: 'god-of-war-ragnarok',
		reviewerName: 'Helena Brandt',
		text: 'Teka-tekinya sering diselesaikan companion sebelum saya sempat berpikir.',
		rating: 3,
		createdAt: '2025-01-30T09:55:00.000Z',
	},
	{
		id: 'review-stray-1',
		gameId: 'stray',
		reviewerName: 'Bunga Lestari',
		text: 'Selesai dalam satu malam dan saya tidak keberatan sama sekali.',
		rating: 4,
		createdAt: '2025-01-17T21:25:00.000Z',
	},
	{
		id: 'review-it-takes-two-1',
		gameId: 'it-takes-two',
		reviewerName: 'Fajar Nugroho',
		text: 'Dimainkan bareng pasangan sampai tamat. Tiap babak menemukan mainan baru.',
		rating: 5,
		createdAt: '2025-01-16T16:40:00.000Z',
	},
	{
		id: 'review-deathloop-1',
		gameId: 'deathloop',
		reviewerName: 'Marco Silva',
		text: 'Menyusun satu hari sempurna terasa seperti memecahkan teka-teki besar.',
		rating: 4,
		createdAt: '2025-01-14T13:05:00.000Z',
	},
	{
		id: 'review-psychonauts-1',
		gameId: 'psychonauts-2',
		reviewerName: 'Ayu Wulandari',
		text: 'Level yang dibangun dari isi kepala tokoh membuat platformer ini sulit dilupakan.',
		rating: 5,
		createdAt: '2025-01-13T10:30:00.000Z',
	},
	{
		id: 'review-tlou2-1',
		gameId: 'the-last-of-us-part-ii',
		reviewerName: 'Reza Alamsyah',
		text: 'Tidak nyaman dimainkan, dan memang seharusnya begitu. Saya menghargainya.',
		rating: 5,
		createdAt: '2025-01-12T19:15:00.000Z',
	},
	{
		id: 'review-tlou2-2',
		gameId: 'the-last-of-us-part-ii',
		reviewerName: 'Katrin Møller',
		text: 'Paruh keduanya terlalu panjang buat saya, tapi aktingnya kelas atas.',
		rating: 3,
		createdAt: '2025-01-31T07:50:00.000Z',
	},
	{
		id: 'review-tsushima-1',
		gameId: 'ghost-of-tsushima',
		reviewerName: 'Yusuf Hakim',
		text: 'Mengganti penunjuk jalan dengan arah angin adalah keputusan terbaiknya.',
		rating: 5,
		createdAt: '2025-01-11T12:00:00.000Z',
	},
	{
		id: 'review-gow-1',
		gameId: 'god-of-war',
		reviewerName: 'Laras Ayuningtyas',
		text: 'Kamera tanpa potongan membuat momen sepinya lebih terasa daripada pertarungannya.',
		rating: 5,
		createdAt: '2025-01-10T17:35:00.000Z',
	},
	{
		id: 'review-botw-1',
		gameId: 'breath-of-the-wild',
		reviewerName: 'Bagus Wirawan',
		text: 'Memanjat apa pun yang terlihat masih terasa luar biasa sampai sekarang.',
		rating: 5,
		createdAt: '2025-01-09T08:20:00.000Z',
	},
	{
		id: 'review-botw-2',
		gameId: 'breath-of-the-wild',
		reviewerName: 'Elena Rossi',
		text: 'Senjata yang gampang patah bikin kesal sampai saya berhenti menimbun.',
		rating: 4,
		createdAt: '2025-01-08T14:45:00.000Z',
	},
	{
		id: 'review-witcher-1',
		gameId: 'witcher-3-wild-hunt',
		reviewerName: 'Lena Vogel',
		text: 'Kontrak sampingannya ditulis lebih serius daripada misi utama kebanyakan game.',
		rating: 5,
		createdAt: '2025-01-07T10:05:00.000Z',
	},
	{
		id: 'review-witcher-2',
		gameId: 'witcher-3-wild-hunt',
		reviewerName: 'Adit Pranata',
		text: 'Sistem tempurnya bagian terlemah, dan tetap tidak membuat saya berhenti.',
		rating: 4,
		createdAt: '2025-01-06T20:30:00.000Z',
	},
]
